"""Consolidate latest worker snapshots OR raw event files, without mixing units."""
import argparse
from collections import Counter
from datetime import datetime, timezone
import json
from pathlib import Path

EXPECTED_WORKERS = ('BOOM','CRASH','JUMP','STEP','VOLATILITY_1','VOLATILITY_2','VOLATILITY_3','VOLATILITY_4')


def process_worker_logs(logs_directory, input_mode='snapshots', emit=True):
    if input_mode not in {'snapshots','events'}:
        raise ValueError('input_mode must be snapshots or events')
    selected, events, errors = {}, [], []
    files = sorted(Path(logs_directory).rglob('*.json'))
    for path in files:
        try:
            data=json.loads(path.read_text(encoding='utf-8-sig'))
            for record in data if isinstance(data,list) else [data]:
                if not isinstance(record,dict):
                    continue
                snapshot='status_counts' in record and 'total_evaluations' in record
                if input_mode=='snapshots':
                    worker=record.get('bot_name')
                    if not snapshot or worker not in EXPECTED_WORKERS:
                        continue
                    # ISO UTC timestamps are generated by the tracker.
                    key=(record.get('start_time',''),record.get('timestamp',''))
                    if worker not in selected or key>selected[worker][0]:
                        selected[worker]=(key,record,str(path))
                elif not snapshot and 'status' in record:
                    events.append(record)
        except (OSError,ValueError,TypeError) as exc:
            errors.append(dict(file=str(path),error=str(exc)))
    statuses, tags, reasons, stages = Counter(), Counter(), Counter(), Counter()
    total=0
    limitations=[]
    rows=[v[1] for v in selected.values()] if input_mode=='snapshots' else events
    for record in rows:
        if input_mode=='snapshots':
            total+=int(record['total_evaluations'])
            statuses.update(record['status_counts'])
            tags.update(record.get('m5_diagnostic_tags',{}))
            if record.get('telemetry_schema_version') != 3:
                limitations.append(record['bot_name']+': not a v3 telemetry session')
            stages.update(record.get('pipeline_funnel',{}).get('stage_counts',{}))
            if 'veto_reason_counts' in record:
                reasons.update(record['veto_reason_counts'])
            else:
                reasons.update(dict(record.get('top_3_rejection_reasons',[])))
                limitations.append(record['bot_name']+': historical snapshot only has top 3 reasons')
        else:
            total+=1
            statuses[record.get('status','UNKNOWN')]+=1
            detail=record.get('m5_detail') or record.get('m5_eval') or {}
            tags[record.get('diagnostic_tag',detail.get('diagnostic_tag','NOT_TAGGED'))]+=1
            reasons.update(set(record.get('reasons',[])))
    report=dict(timestamp=datetime.now(timezone.utc).isoformat(), input_mode=input_mode,
        total_evaluations=total, statuses=dict(statuses), diagnostic_tags=dict(tags),
        status_pct={k:round(100*v/max(1,total),2) for k,v in statuses.items()},
        diagnostic_pct={k:round(100*v/max(1,total),2) for k,v in tags.items()},
        top_rejection_reasons=reasons.most_common(8), pipeline_stage_counts=dict(stages),
        workers={k:dict(file=v[2],start_time=v[1].get('start_time'),updated_at=v[1].get('timestamp'),
                        schema=v[1].get('telemetry_schema_version'),evaluations=v[1]['total_evaluations']) for k,v in selected.items()},
        missing_workers=[w for w in EXPECTED_WORKERS if w not in selected] if input_mode=='snapshots' else [],
        limitations=limitations, errors=errors,
        scope='SCORING_CANDIDATES_NOT_EXECUTED_ORDERS; pipeline counts use a separate denominator')
    if emit:
        print(json.dumps(report,ensure_ascii=True,indent=2))
    return report


if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('logs_directory',nargs='?',default=str(Path(__file__).resolve().parents[1]/'storage/runtime/smc_telemetry'))
    parser.add_argument('--input-mode',choices=['snapshots','events'],default='snapshots')
    parser.add_argument('--output')
    args=parser.parse_args()
    report=process_worker_logs(args.logs_directory,args.input_mode)
    if args.output:
        output=Path(args.output);output.parent.mkdir(parents=True,exist_ok=True)
        output.write_text(json.dumps(report,ensure_ascii=True,indent=2),encoding='utf-8')
